# coding=utf-8
"""Schema constants for neutral receiver integration metadata."""

DETECTOR_CORE_PROFILE_SCHEMA_VERSION = "pilotproxy_detector_core_profile_v2"
RECEIVER_PROFILE_SCHEMA_VERSION = "fstat_receiver_profile_v1"
STREAM_LAYOUT_SCHEMA_VERSION = "fstat_stream_layout_v1"
STREAM_MAP_SCHEMA_VERSION = "fstat_stream_map_v1"

DETECTOR_CORE_ID_PILOT_PROXY_CUDA_V1 = "pilotproxy_cuda_fstat_v1"

COMBINE_MODE_COMBINED_STREAMS = "incoherent_power_sum_over_streams"
COMBINE_MODE_PER_STREAM_DIAGNOSTIC = "per_stream_diagnostic"

QUANTIZATION_SCALE_MODE_GLOBAL = "global"
QUANTIZATION_SCALE_MODE_PER_STREAM = "per_stream"
QUANTIZATION_SCALE_MODE_PROVIDED = "provided"
SUPPORTED_QUANTIZATION_SCALE_MODES = frozenset(
    {
        QUANTIZATION_SCALE_MODE_GLOBAL,
        QUANTIZATION_SCALE_MODE_PER_STREAM,
        QUANTIZATION_SCALE_MODE_PROVIDED,
    }
)

__all__ = [
    "COMBINE_MODE_COMBINED_STREAMS",
    "COMBINE_MODE_PER_STREAM_DIAGNOSTIC",
    "DETECTOR_CORE_ID_PILOT_PROXY_CUDA_V1",
    "DETECTOR_CORE_PROFILE_SCHEMA_VERSION",
    "QUANTIZATION_SCALE_MODE_GLOBAL",
    "QUANTIZATION_SCALE_MODE_PER_STREAM",
    "QUANTIZATION_SCALE_MODE_PROVIDED",
    "RECEIVER_PROFILE_SCHEMA_VERSION",
    "STREAM_LAYOUT_SCHEMA_VERSION",
    "STREAM_MAP_SCHEMA_VERSION",
    "SUPPORTED_QUANTIZATION_SCALE_MODES",
]
