# coding=utf-8
"""Schema constants for neutral receiver integration metadata."""

from pilot_proxy.detector_geometry import (
    COMBINE_MODE_COMBINED_STREAMS,
    COMBINE_MODE_PER_STREAM_DIAGNOSTIC,
    STREAM_LAYOUT_SCHEMA_NAME,
    STREAM_LAYOUT_SCHEMA_REVISION,
    STREAM_LAYOUT_SCHEMA_TOKEN,
)
from pilot_proxy.schema_identity import schema_token

DETECTOR_CORE_PROFILE_SCHEMA_NAME = "pilotproxy_detector_core_profile"
DETECTOR_CORE_PROFILE_SCHEMA_REVISION = 1
DETECTOR_CORE_PROFILE_SCHEMA_TOKEN = schema_token(
    DETECTOR_CORE_PROFILE_SCHEMA_NAME, DETECTOR_CORE_PROFILE_SCHEMA_REVISION
)
RECEIVER_PROFILE_SCHEMA_NAME = "pilotproxy_receiver_profile"
RECEIVER_PROFILE_SCHEMA_REVISION = 1
RECEIVER_PROFILE_SCHEMA_TOKEN = schema_token(
    RECEIVER_PROFILE_SCHEMA_NAME, RECEIVER_PROFILE_SCHEMA_REVISION
)
STREAM_MAP_SCHEMA_NAME = "pilotproxy_stream_map"
STREAM_MAP_SCHEMA_REVISION = 1
STREAM_MAP_SCHEMA_TOKEN = schema_token(
    STREAM_MAP_SCHEMA_NAME, STREAM_MAP_SCHEMA_REVISION
)

DETECTOR_CORE_ID_PILOT_PROXY_CUDA_LOCAL_REFERENCE_POWER_RATIO = (
    "pilotproxy_cuda_local_reference_power_ratio"
)

QUANTIZATION_SCALE_MODE_GLOBAL = "global"
QUANTIZATION_SCALE_MODE_PER_STREAM = "per_stream"
QUANTIZATION_SCALE_MODE_PROVIDED = "provided"
SUPPORTED_QUANTIZATION_SCALE_MODES = frozenset({
    QUANTIZATION_SCALE_MODE_GLOBAL,
    QUANTIZATION_SCALE_MODE_PER_STREAM,
    QUANTIZATION_SCALE_MODE_PROVIDED,
})

__all__ = [
    "COMBINE_MODE_COMBINED_STREAMS",
    "COMBINE_MODE_PER_STREAM_DIAGNOSTIC",
    "DETECTOR_CORE_ID_PILOT_PROXY_CUDA_LOCAL_REFERENCE_POWER_RATIO",
    "DETECTOR_CORE_PROFILE_SCHEMA_NAME",
    "DETECTOR_CORE_PROFILE_SCHEMA_REVISION",
    "DETECTOR_CORE_PROFILE_SCHEMA_TOKEN",
    "QUANTIZATION_SCALE_MODE_GLOBAL",
    "QUANTIZATION_SCALE_MODE_PER_STREAM",
    "QUANTIZATION_SCALE_MODE_PROVIDED",
    "RECEIVER_PROFILE_SCHEMA_NAME",
    "RECEIVER_PROFILE_SCHEMA_REVISION",
    "RECEIVER_PROFILE_SCHEMA_TOKEN",
    "STREAM_LAYOUT_SCHEMA_NAME",
    "STREAM_LAYOUT_SCHEMA_REVISION",
    "STREAM_LAYOUT_SCHEMA_TOKEN",
    "STREAM_MAP_SCHEMA_NAME",
    "STREAM_MAP_SCHEMA_REVISION",
    "STREAM_MAP_SCHEMA_TOKEN",
    "SUPPORTED_QUANTIZATION_SCALE_MODES",
]
