#!/usr/bin/env python3
"""Generate docs/generated/specs.tex from the code, configs, and manifest.

Single-sources the volatile numbers shared by the Data Sheet and User Guide
so the documents cannot drift from the implementation: versions, detector
geometry, fine-reduction constants, the null_power_ratio range and adaptive-placement
facts recomputed from the shipped weight manifest, weight-bank digests, and
derived dB quantities. Stdlib only; no GPU, no third-party imports.

Usage:  python tools/generate_doc_specs.py   (from the repository root)
The `make docs` target runs this before latexmk.
"""
from __future__ import annotations

import hashlib
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "generated" / "specs.tex"

ADC_HZ = 800e6
PFB_POINTS = 2048
COARSE_HZ = ADC_HZ / PFB_POINTS                    # 390625.0
K = 128                                            # detector window samples
DETECTOR_BIN_HZ = COARSE_HZ / K                    # 3051.7578125
FINE_PAD_FACTOR = 2
FINE_NUM_BINS = FINE_PAD_FACTOR * K                # 256
FINE_BIN_HZ = DETECTOR_BIN_HZ / FINE_NUM_BINS      # 11.920928955078125
DTV_BW_HZ = 6.0e6
CHIME_STREAMS = 2048
FRAME_SAMPLES = 16384


def _die(msg: str) -> None:
    print(f"generate_doc_specs: {msg}", file=sys.stderr)
    raise SystemExit(1)


def package_version() -> str:
    text = (ROOT / "pyproject.toml").read_text()
    m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.M)
    if not m:
        _die("version not found in pyproject.toml")
    return m.group(1)


def kernel_core_version() -> str:
    text = (ROOT / "cuda" / "config.h").read_text()
    parts = {}
    for field in ("MAJOR", "MINOR", "PATCH"):
        m = re.search(rf"#define\s+FSTAT_CORE_VERSION_{field}\s+(\d+)", text)
        if not m:
            _die(f"FSTAT_CORE_VERSION_{field} not found in cuda/config.h")
        parts[field] = m.group(1)
    return "{MAJOR}.{MINOR}.{PATCH}".format(**parts)


def sha256_short(path: Path, n: int = 16) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()[:n]


def manifest_facts() -> dict:
    man = json.loads(
        (ROOT / "weights" / "chime_dtv_weights_k128.bin.manifest.json").read_text()
    )
    layout = man["target_reference_layout"]
    mus, adaptive = [], []
    for entry in layout:
        t = int(entry["target_norm_sq"])
        r = int(entry["reference_norm_sum_sq"])
        mus.append(2.0 * t / r)
        if entry.get("adaptive_reference_placement"):
            adaptive.append(int(entry["physical_channel"]))
    if not mus:
        _die("empty target_reference_layout")
    return {
        "null_power_ratio_min": min(mus),
        "null_power_ratio_max": max(mus),
        "n_channels": len(layout),
        "adaptive_channels": adaptive,
    }


def capture_loss_db(offset_hz: float) -> float:
    x = offset_hz / DETECTOR_BIN_HZ
    s = math.sin(math.pi * x) / (math.pi * x)
    return -20.0 * math.log10(s)


def main() -> int:
    facts = manifest_facts()
    if facts["adaptive_channels"] != [14]:
        # The documents state DTV 14 is the only adaptive case; refuse to
        # generate silently inconsistent macros if the bank changes.
        _die(
            "adaptive channels in manifest are "
            f"{facts['adaptive_channels']}; update the documents' placement "
            "statements before regenerating."
        )
    bandwidth_spread_db = 10.0 * math.log10(DTV_BW_HZ / DETECTOR_BIN_HZ)

    lines = [
        "% Generated by tools/generate_doc_specs.py -- DO NOT EDIT.",
        "% Regenerate with: python tools/generate_doc_specs.py",
        f"\\newcommand{{\\ppPackageVersion}}{{{package_version()}}}",
        f"\\newcommand{{\\ppKernelCoreVersion}}{{{kernel_core_version()}}}",
        f"\\newcommand{{\\ppDetectorWindowSamples}}{{{K}}}",
        f"\\newcommand{{\\ppCoarseSpacingkHz}}{{{COARSE_HZ / 1e3:.3f}}}",
        f"\\newcommand{{\\ppDetectorBinHz}}{{{DETECTOR_BIN_HZ:.11g}}}",
        f"\\newcommand{{\\ppFinePadFactor}}{{{FINE_PAD_FACTOR}}}",
        f"\\newcommand{{\\ppFineNumBins}}{{{FINE_NUM_BINS}}}",
        f"\\newcommand{{\\ppFineBinHz}}{{{FINE_BIN_HZ:.6f}}}",
        f"\\newcommand{{\\ppWindowsPerStream}}{{{FRAME_SAMPLES // K}}}",
        f"\\newcommand{{\\ppChimeStreams}}{{{CHIME_STREAMS}}}",
        "\\newcommand{\\ppChimeRowsPerFrame}{"
        f"{CHIME_STREAMS * (FRAME_SAMPLES // K):,}".replace(",", "{,}") + "}",
        f"\\newcommand{{\\ppBandwidthSpreadDb}}{{{bandwidth_spread_db:.3f}}}",
        f"\\newcommand{{\\ppMuZeroMin}}{{{facts['null_power_ratio_min']:.10f}}}",
        f"\\newcommand{{\\ppMuZeroMax}}{{{facts['null_power_ratio_max']:.10f}}}",
        f"\\newcommand{{\\ppWeightChannelCount}}{{{facts['n_channels']}}}",
        f"\\newcommand{{\\ppCaptureLossThreeHundredDb}}{{{capture_loss_db(300.0):.4f}}}",
        f"\\newcommand{{\\ppCaptureLossFiveHundredDb}}{{{capture_loss_db(500.0):.4f}}}",
        f"\\newcommand{{\\ppCaptureLossEdgeDb}}{{{capture_loss_db(DETECTOR_BIN_HZ / 2.0):.2f}}}",
        "\\newcommand{\\ppCoherentGainDb}{"
        + f"{10.0 * math.log10(math.sqrt(FRAME_SAMPLES // K)):.1f}" + "}",
        "\\newcommand{\\ppWeightBankShaShort}{"
        + sha256_short(ROOT / "weights" / "chime_dtv_weights_k128.bin") + "}",
        "\\newcommand{\\ppWeightManifestShaShort}{"
        + sha256_short(
            ROOT / "weights" / "chime_dtv_weights_k128.bin.manifest.json"
        ) + "}",
        "\\newcommand{\\ppSchemaVThree}{pilotproxy\\_detector\\_datatrawl\\_v3}",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
